// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentService.Data;

#nullable disable

namespace StudentService.Migrations
{
    [DbContext(typeof(StudentServiceContext))]
    [Migration("20230706124006_migration 1.0")]
    partial class migration10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentService.Models.CollegeYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CollegeYear");

                    b.HasData(
                        new
                        {
                            Id = new Guid("563104cd-da92-4d00-81af-1f9c21c3a738"),
                            Year = 1
                        },
                        new
                        {
                            Id = new Guid("a916ea1d-406d-4688-86e4-b4e74b134d69"),
                            Year = 2
                        },
                        new
                        {
                            Id = new Guid("84203ba8-dab9-44b5-b089-f7340f2dfb92"),
                            Year = 3
                        },
                        new
                        {
                            Id = new Guid("9a7d7ebc-d68f-4417-87fa-d217e624b1f2"),
                            Year = 4
                        });
                });

            modelBuilder.Entity("StudentService.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollegeYearId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Enrolled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeYearId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentService.Models.Student", b =>
                {
                    b.HasOne("StudentService.Models.CollegeYear", "CollegeYear")
                        .WithMany("Students")
                        .HasForeignKey("CollegeYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Student_CollegeYear");

                    b.Navigation("CollegeYear");
                });

            modelBuilder.Entity("StudentService.Models.CollegeYear", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
